all: Part1-Plot Part2-Split Part3-Train

Part1-Plot:
	python3 Part1-Plot.py

Part2-Split:
	python3 Part2-Split.py

Part3-Train:
	python3 Part3-Train.py

clean:
	rm -f &.pyc __pycache__/* 2>/dev/null || true